export const ALERT = "ALERT";
export const REFETCH_CHATS = "REFETCH_CHATS";
export const NEW_ATTACHMENT = "NEW_ATTACHMENT";
export const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
export const NEW_MESSAGE = "NEW_MESSAGE";

// Settings
export const BASE_LISTED = "BASE_LISTED"; 
export const BASE_CREATED = "BASE_CREATED"; 
export const BASE_UPDATED = "BASE_UPDATED"; 
export const BASE_DELETED = "BASE_DELETED";

export const ADMIN_HERO_LISTED = "ADMIN_HERO_LISTED"; 
export const ADMIN_HERO_CREATED = "ADMIN_HERO_CREATED"; 
export const ADMIN_HERO_UPDATED = "ADMIN_HERO_UPDATED"; 
export const ADMIN_HERO_DELETED = "ADMIN_HERO_DELETED";

export const NOTIFICATION_LISTED = "NOTIFICATION_LISTED"; 
export const NOTIFICATION_CREATED = "NOTIFICATION_CREATED"; 
export const NOTIFICATION_UPDATED = "NOTIFICATION_UPDATED"; 
export const NOTIFICATION_DELETED = "NOTIFICATION_DELETED";

// Administration
export const USER_LISTED = "USER_LISTED"; 
export const USER_CREATED = "USER_CREATED"; 
export const USER_UPDATED = "USER_UPDATED"; 
export const USER_DELETED = "USER_DELETED";

export const ROLE_LISTED = "ROLE_LISTED"; 
export const ROLE_CREATED = "ROLE_CREATED"; 
export const ROLE_UPDATED = "ROLE_UPDATED"; 
export const ROLE_DELETED = "ROLE_DELETED";

export const MENU_LISTED = "MENU_LISTED"; 
export const MENU_CREATED = "MENU_CREATED"; 
export const MENU_UPDATED = "MENU_UPDATED"; 
export const MENU_DELETED = "MENU_DELETED";

// Main
export const HERO_LISTED = "HERO_LISTED"; 
export const HERO_CREATED = "HERO_CREATED"; 
export const HERO_UPDATED = "HERO_UPDATED"; 
export const HERO_DELETED = "HERO_DELETED";

export const COUNTER_LISTED = "COUNTER_LISTED"; 
export const COUNTER_CREATED = "COUNTER_CREATED"; 
export const COUNTER_UPDATED = "COUNTER_UPDATED"; 
export const COUNTER_DELETED = "COUNTER_DELETED";

export const ABOUT_LISTED = "ABOUT_LISTED"; 
export const ABOUT_CREATED = "ABOUT_CREATED"; 
export const ABOUT_UPDATED = "ABOUT_UPDATED"; 
export const ABOUT_DELETED = "ABOUT_DELETED";

export const SERVICE_LISTED = "SERVICE_LISTED"; 
export const SERVICE_CREATED = "SERVICE_CREATED"; 
export const SERVICE_UPDATED = "SERVICE_UPDATED"; 
export const SERVICE_DELETED = "SERVICE_DELETED";

export const BRANCH_SECTION_LISTED = "BRANCH_SECTION_LISTED"; 
export const BRANCH_SECTION_CREATED = "BRANCH_SECTION_CREATED"; 
export const BRANCH_SECTION_UPDATED = "BRANCH_SECTION_UPDATED"; 
export const BRANCH_SECTION_DELETED = "BRANCH_SECTION_DELETED";

export const BRANCH_GROUP_LISTED = "BRANCH_GROUP_LISTED"; 
export const BRANCH_GROUP_CREATED = "BRANCH_GROUP_CREATED"; 
export const BRANCH_GROUP_UPDATED = "BRANCH_GROUP_UPDATED"; 
export const BRANCH_GROUP_DELETED = "BRANCH_GROUP_DELETED";

export const BRANCH_LISTED = "BRANCH_LISTED"; 
export const BRANCH_CREATED = "BRANCH_CREATED"; 
export const BRANCH_UPDATED = "BRANCH_UPDATED"; 
export const BRANCH_DELETED = "BRANCH_DELETED";

export const PROJECT_SECTION_LISTED = "PROJECT_SECTION_LISTED"; 
export const PROJECT_SECTION_CREATED = "PROJECT_SECTION_CREATED"; 
export const PROJECT_SECTION_UPDATED = "PROJECT_SECTION_UPDATED"; 
export const PROJECT_SECTION_DELETED = "PROJECT_SECTION_DELETED";

export const PROJECT_GROUP_LISTED = "PROJECT_GROUP_LISTED"; 
export const PROJECT_GROUP_CREATED = "PROJECT_GROUP_CREATED"; 
export const PROJECT_GROUP_UPDATED = "PROJECT_GROUP_UPDATED"; 
export const PROJECT_GROUP_DELETED = "PROJECT_GROUP_DELETED";

export const PROJECT_LISTED = "PROJECT_LISTED"; 
export const PROJECT_CREATED = "PROJECT_CREATED"; 
export const PROJECT_UPDATED = "PROJECT_UPDATED"; 
export const PROJECT_DELETED = "PROJECT_DELETED";

export const PROGRAM_SECTION_LISTED = "PROGRAM_SECTION_LISTED"; 
export const PROGRAM_SECTION_CREATED = "PROGRAM_SECTION_CREATED"; 
export const PROGRAM_SECTION_UPDATED = "PROGRAM_SECTION_UPDATED"; 
export const PROGRAM_SECTION_DELETED = "PROGRAM_SECTION_DELETED";

export const PROGRAM_LISTED = "PROGRAM_LISTED"; 
export const PROGRAM_CREATED = "PROGRAM_CREATED"; 
export const PROGRAM_UPDATED = "PROGRAM_UPDATED"; 
export const PROGRAM_DELETED = "PROGRAM_DELETED";

// Asset
export const STATIC_DATA_LISTED = "STATIC_DATA_LISTED"; 
export const STATIC_DATA_CREATED = "STATIC_DATA_CREATED"; 
export const STATIC_DATA_UPDATED = "STATIC_DATA_UPDATED"; 
export const STATIC_DATA_DELETED = "STATIC_DATA_DELETED";


